# Generated by Django 5.0.3 on 2026-07-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_itemcomanda_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomanda',
            name='entregar_junto_com_prato',
            field=models.BooleanField(default=False),
        ),
    ]
