# Generated by Django 5.0.3 on 2026-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_itemcomanda_entregar_junto_com_prato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcomanda',
            name='entregar_junto_com_prato',
        ),
        migrations.AlterField(
            model_name='itemcomanda',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente (Novo)'), ('Em Preparo', 'Em Preparo'), ('Pronto', 'Pronto (Aguardando Retirada)'), ('Entregue', 'Entregue'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
    ]
