# Generated by Django 5.0.3 on 2026-07-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0004_remove_itemcomanda_entregar_junto_com_prato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomanda',
            name='entregar_junto_com_prato',
            field=models.BooleanField(default=False),
        ),
    ]
