# Generated by Django 5.0.3 on 2026-07-30 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_itemcomanda_entregar_junto_com_prato'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Referência única para a API da Focus', unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Emissão'), ('processando', 'Processando na Sefaz'), ('emitida', 'Autorizada (Emitida)'), ('erro', 'Rejeitada/Erro Sefaz'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('chave_acesso', models.CharField(blank=True, help_text='Chave de 44 dígitos da Sefaz', max_length=44, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=5, null=True)),
                ('caminho_xml', models.URLField(blank=True, max_length=500, null=True)),
                ('caminho_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('mensagem_sefaz', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_fiscal', to='pdv.comanda')),
            ],
        ),
    ]
