# Generated by Django 5.0.3 on 2026-07-12 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('L', 'Litro'), ('G', 'Grama'), ('ML', 'Mililitro')], default='UN', max_length=2)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.insumo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='estoque.produto')),
            ],
        ),
    ]
