# Generated by Django 5.0.3 on 2026-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='setor_preparo',
            field=models.CharField(choices=[('COZINHA', 'Cozinha'), ('BAR', 'Bar'), ('COPA', 'Copa / Geladeira')], default='COZINHA', max_length=20),
        ),
    ]
