# Generated by Django 5.0.3 on 2026-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_setor_preparo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='setor_preparo',
        ),
        migrations.AddField(
            model_name='produto',
            name='setor',
            field=models.CharField(choices=[('Cozinha', 'Cozinha'), ('Copa', 'Copa'), ('Bar', 'Bar')], default='Cozinha', max_length=20),
        ),
    ]
